// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateBooking(arg1:models.CreateBookingInput):Promise<models.Booking>;

export function CreateBoothLocation(arg1:models.CreateBoothLocationInput):Promise<models.BoothLocation>;

export function CreateExpense(arg1:models.CreateExpenseInput):Promise<models.Expense>;

export function CreateQueueSession(arg1:models.CreateQueueSessionInput):Promise<models.QueueSession>;

export function CreateTemplate(arg1:models.CreateTemplateInput):Promise<models.Template>;

export function DeleteBooking(arg1:number):Promise<boolean>;

export function DeleteBoothLocation(arg1:number):Promise<boolean>;

export function DeleteExpense(arg1:number):Promise<boolean>;

export function DeleteQueueSession(arg1:number):Promise<boolean>;

export function GetBookings():Promise<Array<models.Booking>>;

export function GetBoothLocations():Promise<Array<models.BoothLocation>>;

export function GetCurrentUser():Promise<models.User>;

export function GetDashboardData():Promise<models.DashboardData>;

export function GetExpenses():Promise<Array<models.Expense>>;

export function GetQueueSessions():Promise<Array<models.QueueSession>>;

export function GetTemplates():Promise<Array<models.Template>>;

export function GetTodayQueueStats():Promise<models.TodayStats>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function Logout():Promise<boolean>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<models.User>;

export function ToggleBoothStatus(arg1:number):Promise<models.BoothLocation>;

export function ToggleTemplate(arg1:number):Promise<models.Template>;

export function UpdateBookingStatus(arg1:number,arg2:string):Promise<models.Booking>;

export function UpdateBoothLocation(arg1:number,arg2:models.CreateBoothLocationInput):Promise<models.BoothLocation>;

export function UpdatePassword(arg1:string,arg2:string):Promise<boolean>;

export function UpdateProfile(arg1:string,arg2:string):Promise<models.User>;

export function UpdateQueueSession(arg1:number,arg2:models.CreateQueueSessionInput):Promise<models.QueueSession>;

export function UpdateQueueSessionStatus(arg1:number,arg2:string):Promise<models.QueueSession>;
