// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBooking(arg1) {
  return window['go']['main']['App']['CreateBooking'](arg1);
}

export function CreateBoothLocation(arg1) {
  return window['go']['main']['App']['CreateBoothLocation'](arg1);
}

export function CreateExpense(arg1) {
  return window['go']['main']['App']['CreateExpense'](arg1);
}

export function CreateQueueSession(arg1) {
  return window['go']['main']['App']['CreateQueueSession'](arg1);
}

export function CreateTemplate(arg1) {
  return window['go']['main']['App']['CreateTemplate'](arg1);
}

export function DeleteBooking(arg1) {
  return window['go']['main']['App']['DeleteBooking'](arg1);
}

export function DeleteBoothLocation(arg1) {
  return window['go']['main']['App']['DeleteBoothLocation'](arg1);
}

export function DeleteExpense(arg1) {
  return window['go']['main']['App']['DeleteExpense'](arg1);
}

export function DeleteQueueSession(arg1) {
  return window['go']['main']['App']['DeleteQueueSession'](arg1);
}

export function GetBookings() {
  return window['go']['main']['App']['GetBookings']();
}

export function GetBoothLocations() {
  return window['go']['main']['App']['GetBoothLocations']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetExpenses() {
  return window['go']['main']['App']['GetExpenses']();
}

export function GetQueueSessions() {
  return window['go']['main']['App']['GetQueueSessions']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetTodayQueueStats() {
  return window['go']['main']['App']['GetTodayQueueStats']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function ToggleBoothStatus(arg1) {
  return window['go']['main']['App']['ToggleBoothStatus'](arg1);
}

export function ToggleTemplate(arg1) {
  return window['go']['main']['App']['ToggleTemplate'](arg1);
}

export function UpdateBookingStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateBookingStatus'](arg1, arg2);
}

export function UpdateBoothLocation(arg1, arg2) {
  return window['go']['main']['App']['UpdateBoothLocation'](arg1, arg2);
}

export function UpdatePassword(arg1, arg2) {
  return window['go']['main']['App']['UpdatePassword'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateQueueSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateQueueSession'](arg1, arg2);
}

export function UpdateQueueSessionStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateQueueSessionStatus'](arg1, arg2);
}
